### ISSUE TITLE
Вывод различных типов аттачей в сообщении

### ISSUE THREAD

**Issue by psdcoder** [shri-zoo/pepo#132]

**Comment by tadatuta** [comment]
`http://mini.s-shot.ru/разрешение/размер/формат/?адрес страницы`

**разрешение** - указывается в пикселях, например (1024x768), для полноразмерного скриншота указываем только ширину (1024)
**размер** - указывается ширина масштабированной картинки
**формат** - может принимать два значения (JPEG|PNG), по умолчанию "JPEG"

пример: `http://mini.s-shot.ru/1024x768/400/jpeg/?http://www.site.ru`
